# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://krazedkrish.com/projects/
title: krazedkrish
email: krazedkrish@gmail.com
author: Shalil Awaley
description: > # "This is my awesome site. It has projects and blog articles related to linux, ruby, rails, python, javascript, jquery and other tech related fields"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/krazedkrish
  - title: github
    url: https://github.com/krazedkrish
  - title: linkedin
    url: https://np.linkedin.com/pub/shalil-awaley/69/618/b21
